# dvwa_host_cf.yaml

AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-04b70fa74e45c3917"
      InstanceType: "t2.medium"
      EbsOptimized: false
      SecurityGroupIds:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            Encrypted: false
            VolumeSize: 8
            VolumeType: "gp3"
            DeleteOnTermination: true
      UserData: "IyEvYmluL2Jhc2gKc3VkbyBhcHQgdXBkYXRlCnN1ZG8gYXB0IHVwZ3JhZGUgLXkKc3VkbyBhcHQgaW5zdGFsbCAteSBwaHAgYXBhY2hlMiBtYXJpYWRiLXNlcnZlciBwaHAtbXlzcWxpIHBocC1nZCBsaWJhcGFjaGUyLW1vZC1waHAKbWtkaXIgLXAgL3Zhci93d3cvaHRtbCAmJiBjZCAiJF8iCnN1ZG8gZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9kaWdpbmluamEvRFZXQQpjZCBEVldBL2NvbmZpZwpzdWRvIGNwIGNvbmZpZy5pbmMucGhwLmRpc3QgY29uZmlnLmluYy5waHAKc3VkbyBteXNxbCAtdSByb290IC1lICJjcmVhdGUgZGF0YWJhc2UgZHZ3YTsgY3JlYXRlIHVzZXIgZHZ3YUBsb2NhbGhvc3QgaWRlbnRpZmllZCBieSAncEBzc3cwcmQnOyBncmFudCBhbGwgb24gZHZ3YS4qIHRvIGR2d2FAbG9jYWxob3N0OyBmbHVzaCBwcml2aWxlZ2VzOyIKc3VkbyBjaGdycCB3d3ctZGF0YSAvdmFyL3d3dy9odG1sL0RWV0EvaGFja2FibGUvdXBsb2Fkcy8Kc3VkbyBjaG1vZCBnK3cgL3Zhci93d3cvaHRtbC9EVldBL2hhY2thYmxlL3VwbG9hZHMvCnN1ZG8gY2hncnAgd3d3LWRhdGEgL3Zhci93d3cvaHRtbC9EVldBL2NvbmZpZy8Kc3VkbyBjaG1vZCBnK3cgL3Zhci93d3cvaHRtbC9EVldBL2NvbmZpZy8Kc3VkbyBzZXJ2aWNlIGFwYWNoZTIgcmVzdGFydApmaWxlPSQoZmluZCAvZXRjIC10eXBlIGYgLW5hbWUgInBocC5pbmkiIDI+JjEgfCBzZWQgMXEgMj4mMSB8IHNlZCAxcSkKc3VkbyBzZWQgIC1pICAtZSAncy9hbGxvd191cmxfaW5jbHVkZSA9IE9mZi9hbGxvd191cmxfaW5jbHVkZSA9IE9uLycgLWUgJ3MvYWxsb3dfdXJsX2ZvcGVuID0gT2ZmL2FsbG93X3VybF9mb3BlbiA9IE9uLycgICRmaWxl"
      Tags:
        - Key: "Name"
          Value: "DVWA Host"
      HibernationOptions:
        Configured: false
      EnclaveOptions:
        Enabled: false

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP, HTTPS, SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
